version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - foodgram_db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: juliasnowbars/foodgram_backend:latest
    restart: always
    volumes:
      - foodgram_static:/app/static/
      - foodgram_media:/app/media/
      - foodgram_redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: juliasnowbars/foodgram_frontend:latest
    volumes:
      - foodgram_frontend:/app/build
  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../frontend/:/app/result_build/

  migrate-and-collectstatic:
    image: juliasnowbars/foodgram_backend:latest
    command:
      - python manage.py migrate --noinput
      - python manage.py collectstatic --noinput
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "83:83"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      # - ../docs/:/usr/share/nginx/html/api/docs/
      - foodgram_static:/var/html/static/
      - foodgram_media:/var/html/media/
      - foodgram_redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    restart: always

volumes:
  foodgram_static:
  foodgram_media:
  foodgram_db:
  foodgram_redoc:
  foodgram_frontend:
